### ISSUE TITLE
Allow tableize method to accept an array of columns

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/more_core_extensions#42]
Currently, using the tableize method is a bit verbose:

    Vm.limit(3).map(&:attributes).tableize(:columns => %w(id type name power_state))

I would like to be able to just do this:

    Vm.limit(3).tableize(%w(id type name power_state))

**Comment by Fryguy** [comment]
Since this is a monkey patch on Array, at a minimum you'd need to_a (as below), but yeah, I like this idea.

```ruby
Vm.limit(3).to_a.tableize(%w(id type name power_state))
```

**Comment by djberg96** [comment]
Oh, I thought you were hooking into ActiveRecord collections.

**Comment by djberg96** [comment]
Eh, not sure how to do it without too many type checking contortions, and I don't use it much. Closing.
