### ISSUE TITLE
Should #delete_blanks be #delete_blanks!

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/more_core_extensions#48]
I was a bit surprised that `Hash#delete_blanks` modified the hash object. I was expecting it to return a new object like `#map`, but I can also see the argument that it mirrors the behavior of `#delete` and `#delete_if`.

What do others think about having a separate `#delete_blanks` which doesn't modify the object?

**Comment by Fryguy** [comment]
:+1:.  The API change would require a major bump though.

**Comment by Fryguy** [comment]
> I can also see the argument that it mirrors the behavior of #delete and #delete_if.

That was actually the original intent.  These are helpers that simplify common delete patterns.

**Comment by Fryguy** [comment]
After thinking this more, I think it's better to leave as is, as it matches the semantics of `delete` and `delete_if`
